site_name: PON dot WIKI
site_url: https://pon.wiki
site_description: >-
  We're unlocking the FTTP edge with the freedom of choice through shared knowledge and open standards while
  empowering SOHO operators by kicking the ISP CPE to the curb
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tilde
  - sane_lists
  - tables
  - toc:
      permalink: true
theme:
  name: material
  palette:
    primary: blue
    accent: blue
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
  custom_dir: overrides
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/isp.js
  - javascripts/swiper.js
hooks:
  - hooks/external_links_md_extension.py
plugins:
  - blog:
      authors: false
      blog_dir: .
      post_excerpt: required
      post_excerpt_max_authors: 0
      post_excerpt_max_categories: 3
      post_url_format: "guides/{slug}"
      pagination_per_page: 5
  - glightbox:
      loop: false
      skip_classes:
        - nolightbox
      zoomable: false
  - redirects:
      redirect_maps:
        guides/install-8311-community-firmware-on-the-bfw-solutions-was-110/index.html: https://pon.wiki/guides/install-the-8311-community-firmware-on-the-was-110/
        guides/masquerade-as-the-bce-inc-home-hub-4000-on-xgs-pon-with-the-bfw-solutions-was-110/index.html: https://pon.wiki/guides/masquerade-as-the-bce-inc-home-hub-4000-with-the-was-110/
        guides/masquerade-as-the-bce-inc-giga-hub-on-xgs-pon-with-the-bfw-solutions-was-110/index.html: https://pon.wiki/guides/masquerade-as-the-bce-inc-giga-hub-with-the-was-110/
        guides/masquerade-as-the-att-inc-bgw320-500-505-on-xgs-pon-with-the-bfw-solutions-was-110/index.html: https://pon.wiki/guides/masquerade-as-the-att-inc-bgw320-500-505-with-the-was-110/
  - search
  - table-reader
watch:
  - includes
nav:
  - GUIDES:
    - index.md
  - GPON:
    - gpon/index.md
    - ONT:
      - Source Photonics:
        - gpon/ont/source-photonics/sps-34-24t-hp-tdfo.md
  - XGS-PON:
    - xgs-pon/index.md
    - ONT:
      - BFW Solutions:
        - xgs-pon/ont/bfw-solutions/was-110.md
      - Potron Technology:
        - X-ONU-SFPP: xgs-pon/ont/potron-technology/x-onu-sfpp.md
  - DISCORD:
    - discord/index.md
    - Quick start: discord/quick-start.md
    - Group buys: discord/group-buys.md
    - Giveaways: discord/giveaways.md
  - ON THE WEB: on-the-web.md
extra:
  analytics:
    provider: google
    property: G-YLNP9LG92G
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/up-n-atom/8311/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to measure the effectiveness of our documentation and whether users find what they're searching
      for. With your consent, you're helping us to make our documentation better.
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/servers/8311-886329492438671420
copyright: CC BY-NC-SA 4.0
repo_url: https://github.com/up-n-atom/8311
repo_name: up-n-atom/8311
